import mongoose from "mongoose";

const productsSchema = mongoose.Schema({
    "group_id": String,
    "type_id": String,
    "category_id": String,
    "brand_id": String,
    "brand_variant_id": String,
    "brand_type_id": String,
    "brand_proc_id": String,
    "proc_id": String,
    "group": Object,
    "type": Object,
    "category": Object,
    "brand": Object,
    "brand_variant": Object,
    "brand_type": Object,
    "brand_proc": Object,
    "code": String,
    "specification": String,
    "notes": String,
    "info": String,
    "disc": Number,
    "reb": Number,
    "sello": Number,
    "md": Number,
    "srp": Number,
    "m00": Number,
    "m0": Number,
    "m1": Number,
    "m2": Number,
    "m3": Number,
    "m3x": Number,
    "cbm": Number,
    "total": Number,
    "dp": Number,
    "svc": Number,
    "aging": String,
    "upload": String,
    "upload2": String,
    "product_number": String,
    "created_by": Date,
    "updated_by": Date,
    "status": String,
    "updated_at": Date,
    "created_at": Date,
    "pricelist_updated_at": Date,
    "disc_formula_excel": Object,
    "reb_formula_excel": Object,
    "sello_formula_excel": Object,
    "stock_in_updated_at": Date,
    "is_bundle": Boolean,
    "m00_formula_excel": Object,
    "m3x_formula_excel": Object,
})

export default productsSchema